### ISSUE TITLE
Keymappings file(s) for Cheatsheet & Other Settings

### ISSUE THREAD

**Issue by Herk2** [benbrastmckie/.config#101]
I forked your .config a couple of days ago and am really liking it.  However, I had major navigation problems with the recent updating of nvim-tree, so I swapped it out for nvim-neo-tree / neo-tree.nvim,  which worked out of the box.

I’d like to use <leader> e to open nvim-neo-tree and <leader> ff to open the fuzzy file search LeaderF.  I looked up your keymappings with  :map <leader>, but wasn’t able to find them in the current .config.  Are they, in fact, there?  (You seem to imply in the Cheatsheet that they were/are.)  If not, could you kindly make them available.

**Comment by benbrastmckie** [comment]
Me too re `nvim-tree`, motivating me to also switch to `neo-tree` a few days ago as well. If it helps, you can find the config I set up in `neo-tree.lua`. If you have not already set up a config session, I recommend proceeding as follows:
  
  - open neovim from any location in the terminal
  - open `config` in the start screen
  - hit `<space>au` to change the current working directory to the location of `init.lua`
  - hit `ctrl+p` to fuzzy find files
  - type `neo-tree.lua` and open the file
  - save the session with `<space>ms`

When you want to get back into the config, now you can revert to your config session wherever you left off instead of starting fresh with `init.lua` each time.

As for opening neo-tree with `<space>e`, I have the keymapping in `whichkey.lua`. I have copied the relevant line for ease:

```
  ["e"] = { "<cmd>Neotree<CR>"                  , "explorer" },
```

You can change around the other keymappings for whichkey (activated by the leader key) there as well, but all other mappings are to be found in `keymaps.lua`.

As for what shows up for me when I run `:verbose map <space>`, it's a long list and you should see something similar.

Let me know if that sorts out the issues you were having.

**Comment by Herk2** [comment]
I completely forgot about WhichKey as a source of mappings.

I’ll digest your use of sessions for configs.  I have never used sessions, but I really liked your video discussion of how you use them and have been meaning to follow suit.

Thanks.

Herk
