### ISSUE TITLE
enable autocomplete by hitting tab

### ISSUE THREAD

**Issue by ammukuttu** [benbrastmckie/.config#112]
In the earlier version of nvim configuration, while typing the words as it appeared came up for autocomplete. It was easy to hit the tab and get it to autocomplete. This was helpful. What is the setting in the current configuration? Tab or arrow keys don't work

please advise

**Comment by benbrastmckie** [comment]
Yes I made `ctrl+j/k` consistent throughout. If you don't like that you can change it around in cmp.lua. Change `<C-j>` to `<Tab>`, and `<C-k>` to `<S-Tab>`. Hopefully that doesn't conflict with anything. You can also use LazyGit with `<space>gg` to see all the past commits. If you checkout one of them in the past, you can then navigate to cmp.lua to see how it was configured. Once you are done, you can revert back to the master branch so that nothing changes about your config.

**Comment by ammukuttu** [comment]
Changing the `<Tab>` or `<S-Tab>` did not work. The `Tab` part was not recorded in any of the previous commits.

I played with several combinations. I found sometime `TAB` (uppercase only) worked in lieu of `<C-j> `worked but then `S-TAB` wouldn't work and sometime `TAB` wouldn't work. It left me confused. I think it is best to keep it as it is. The `Tab` key was just convenient, considering the location of `Ctrl` key. My observation is this configuration is very temperamental.
