### ISSUE TITLE
telescope bibtex to show in cmp suggestions

### ISSUE THREAD

**Issue by babakou9** [benbrastmckie/.config#113]
Hi!

I just watched your youtube video on integrating bibtex in neovim and it mostly works. 

I did the zotero configuration and edited telescope setup like you show in the video and I can cite from my library, but only with the command :
: Telescope bibtex
In your video it seems you have cmp/snippet integration of the possible citations, how did you achieve that ?

cheers

**Comment by benbrastmckie** [comment]
I'm not sure when you last pulled down the config but if you go into Whichkey.lua you should be able to configure key bindings. If you are wondering about the autocomplete, that happens through the lsp which you can configure in cmp.lua. There have since been some improvements to Vimtex via [vimtex-cmp](https://github.com/micangl/cmp-vimtex). I've been meaning to switch over to this but haven't yet. I will try to get to that soon, but in the mean time you might have a look.

**Comment by babakou9** [comment]
thank you for your answer! 
I didn’t pull your config, mine is already quite elaborate, I wouldn’t loose everything. I just followed your video to enable bibtex citations in nvim.
I didn’t know that I could configure keybindings with which key... I only use it as a reminder of my shortcuts... I’ll see that!
I looked in your config for a way to configure the  lsp to get the citations from Telescope but i didn’t find a solution, I’ll try vimtex-cmp.
And actually, Telescope bibtex shows and inserts the citations but they are not rendered when i compile.

I should look further into that without bothering you until I find a way ;)

**Comment by benbrastmckie** [comment]
Hey there, I just integrated `cmp-vimtex` in place of `cmp-omni`. It works great and looks much better than before. It's a pretty easy install. Simply add the plugin in place of omni, add a bit of config to `vimtex.lua`, and some key changes to `cmp.lua`. Hope that helps!
