### ISSUE TITLE
Failed install, Mac Sonoma.14.2 and earlier

### ISSUE THREAD

**Issue by capnahab** [benbrastmckie/.config#115]
This is possibly related to a previous config - I deleted ~/.config/nvim and ~/local/share/nvim before attmeoting this install.
Git pull remote seems to work but on launching nvim I cannot launch :PackerUpdate -  non of the packer commands are recognised. 
~/.local/share/nvim/site/pack/packer/start/packer.nvimq is there.
My ~/.config/nvim/lua/user file structure has not been built.
I think this could all be a packer install issue but not sure how to troubleshoot it.

**Comment by benbrastmckie** [comment]
Hey sorry for the slow reply. Did you get it working? If so, it would be great to post your solution here for others. If not, then I suspect you will need to reinstall packer (refer to their github [page](https://github.com/wbthomason/packer.nvim)).

Note, however, that I have since refactored the config to use lazy.nvim instead which I have found to be much better and does not require that you install packer for it to work. Note that in pulling the new config down, other things may break, so you should be ready to do some other troubleshooting if need be. Hopefully the new config is worth it, and it looks like lazy.nvim will be here for a while, at least until neovim adds a native package manager (if/when that happens).
