### ISSUE TITLE
Tmux configuration error

### ISSUE THREAD

**Issue by Alekssavin** [benbrastmckie/.config#75]
Hi! I've installed alacritty and tmux with your config files.
When I start alacritty, tmux also starts and I get the following error:
 `/home/aleksandr/.tmux.conf:2: no current target`
When I have to press Esc and I am in bash. I have to type `fish` every time to enter fish, it's not set as default for some reason.

I did a bit of googleing the problem and it seems that changing the 2nd line in .tmux.conf removes the error message.
[Check the solution here](https://github.com/tmux/tmux/issues/1598)
Do you have the same problem on your computer?

**Comment by benbrastmckie** [comment]
I don't, however, upon looking up that line in the .tmux.conf file, this is what I found:

```
  bind R source ~/.tmux.conf\\; display "~/.tmux.conf sourced!"
```

I've since changed it to only include a single slash before the semicolon, though I'm not sure this will make much of a difference. But the place where alacritty calls fish is `nvim/alacritty/alacritty.yml`. Is that file in place with the following lines:

```
  shell:
    program: /usr/bin/fish
    args:
      - -l
      - -c
      - "tmux"
```

You might also make sure that fish is in the right spot by running `which fish` in the terminal. If it spits out something different than `/usr/bin/fish`, then change the alacritty.yml file to reflect whatever `which fish` spits out. Hope that helps!

**Comment by Alekssavin** [comment]
> But the place where alacritty calls fish is `nvim/alacritty/alacritty.yml`. 
Do you mean `~/.config/alacritty/alacritty.yml`?
Yes, I have checked it of course and I didn't have to change it because my fish is installed in `/usr/bin/fish`.
That's strange `fish` doesn't run automatically. It even happens when I open `Floatterm` in `nvim`, unlike you I get plain bash shell.

**Comment by benbrastmckie** [comment]
Yes sorry, I do mean that path. Might changing the default shell along these lines do the trick:

```
https://askubuntu.com/questions/26439/how-do-i-set-fish-as-the-default-shell
```

**Comment by Alekssavin** [comment]
> Yes sorry, I do mean that path. Might changing the default shell along these lines do the trick:
> 
> ```
> https://askubuntu.com/questions/26439/how-do-i-set-fish-as-the-default-shell
> ```

I have OpenSuse LEAP 15.2 distro. I studied the page you sent me and was able to successfully switch my systemwide default shell to fish. I like in much better.
Moreover, I removed the extra slash from `.tmux.config' and I get the error message on the startup no more.
You have helped me to deal with the issue. Thank you very much!
