### ISSUE TITLE
Module `session_manager` not found

### ISSUE THREAD

**Issue by alexander-read** [benbrastmckie/.config#93]
The following error is thrown upon entering `nvim` from the terminal:

<img width="771" alt="Screenshot 2023-02-26 at 00 30 03" src="https://user-images.githubusercontent.com/97128707/221385866-2992c453-45e9-4c57-a2a5-b70f62e35191.png">

If I continue into NeoVim and `checkhealth`, I get the following:

<img width="720" alt="Screenshot 2023-02-26 at 00 28 02" src="https://user-images.githubusercontent.com/97128707/221385874-c742ec92-3c2b-4381-8235-7d0bdb32ccad.png">

I checked `plugins.lua` and "Shatur/neovim-session-manager" is there, and I followed the instructions in `config`, so am not sure where this error is coming from.

**Comment by benbrastmckie** [comment]
I'm not too sure myself. I did some searching and looked through the issues in [neovim-session-manager](https://github.com/Shatur/neovim-session-manager/issues) and couldn't find a similar problem. I would suggest posting your issue there, linking that issue here for others to find.

Regarding your `healthcheck` error, are you using [hop](https://github.com/phaazon/hop.nvim)? Does the error go away if you comment out the lines that add the `hop` plugin in your plugins.lua file along with any config files?

**Comment by alexander-read** [comment]
Ok thanks! I'll try that for session manager.

On `checkhealth`, I could not see any lines adding `hop` in `plugins.lua`.
Adding `require'hop'.setup()` to `plugins.lua` resolved the `checkhealth` error, but I'm not sure if I need to add anything to any other config files to make sure hop is working properly.

**Comment by alexander-read** [comment]
I un-installed NeoVim then did a fresh install (along with every package) etc., which seemed to fix this

**Comment by benbrastmckie** [comment]
That's great, glad to hear it!
